# Generated by Django 5.1.2 on 2024-11-20 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=100)),
                ('description', models.TextField(help_text='Описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название темы', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания темы')),
                ('category', models.ForeignKey(help_text='Категория, к которой относится тема', on_delete=django.db.models.deletion.CASCADE, to='forum.category')),
                ('created_by', models.ForeignKey(help_text='Пользователь, создавший тему', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания сообщения')),
                ('created_by', models.ForeignKey(help_text='Пользователь, создавший сообщение', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(help_text='Тема, к которой относится сообщение', on_delete=django.db.models.deletion.CASCADE, to='forum.thread')),
            ],
        ),
    ]
