# Generated by Django 5.1.2 on 2024-11-30 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_address_order_name_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
