# Generated by Django 5.1.2 on 2024-10-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='bonus_points',
        ),
    ]
