# Generated by Django 5.1.2 on 2024-11-03 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0006_tirestorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=50)),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись на обслуживание',
                'verbose_name_plural': 'Записи на обслуживание',
            },
        ),
    ]
