# Generated by Django 5.1.2 on 2024-11-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0011_alter_user_groups_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
