# Generated by Django 5.1.2 on 2024-11-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0012_alter_user_options_alter_user_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirestorage',
            name='tire_model',
            field=models.CharField(default='Неизвестная модель', max_length=50),
        ),
        migrations.AddField(
            model_name='tirestorage',
            name='tire_size',
            field=models.CharField(default='Неизвестный размер', max_length=20),
        ),
    ]
