# Generated by Django 5.1.2 on 2024-11-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0013_tirestorage_tire_model_tirestorage_tire_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirestorage',
            name='quantity',
            field=models.CharField(default='Неизвестное количество', max_length=2),
        ),
    ]
